빌드 명령어 추가

diff --git a/.github/workflows/lighthouse.yaml b/.github/workflows/lighthouse.yaml
--- a/.github/workflows/lighthouse.yaml
+++ b/.github/workflows/lighthouse.yaml
@@ -13,8 +13,8 @@ jobs:
       - name: npm install, build
         run: |
           npm ci
-          npm run dev
+          npm run build
       - name: run Lighthouse CI
         run: |
           npm install -g @lhci/cli
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+          lhci autorun || echo "LHCI failed!"
