빌드 후 정적파일을 lighthoust에서 실행

diff --git a/.github/workflows/lighthouse.yaml b/.github/workflows/lighthouse.yaml
--- a/.github/workflows/lighthouse.yaml
+++ b/.github/workflows/lighthouse.yaml
@@ -6,11 +6,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Audit URLs using Lighthouse
-        uses: treosh/lighthouse-ci-action@v9
+      - name: Use Node.js 17.3.1
+        uses: actions/setup-node@v1
         with:
-          urls: |
-            http://localhost:3000
-          budgetPath: ./budget.json # test performance budgets
-          uploadArtifacts: true # save results as an action artifacts
-          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
+          node-version: 17.3.1
+      - name: npm install, build
+        run: |
+          npm ci
+          npm run build
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli
+          lhci autorun || echo "LHCI failed!"
